base/urls.py
from django.urls import path
from . import views
from .views import BlogList, BlogDetails, BlogCreate, BlogUpdate, BlogDelete, ReviewCreate, ReviewUpdate, ReviewDelete, UserLogin, RegisterUser
from django.contrib.auth.views import LogoutView 

urlpatterns = [
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='blogs'), name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('', BlogList.as_view(), name='blogs'),
    path('blog/<int:pk>/', BlogDetails.as_view(), name='blog'),
    path('blog-create', BlogCreate.as_view(), name='addblog'),
    path('blog-update/<int:pk>/', BlogUpdate.as_view(), name='updateblog'),
    path('blog-delete/<int:pk>/', BlogDelete.as_view(), name='deleteblog'),
    path('blog/<int:pk>/review-create/', ReviewCreate.as_view(), name='addreview'),
    path('review-update/<int:pk>/', ReviewUpdate.as_view(), name='updatereview'),
    path('review-delete/<int:pk>/', ReviewDelete.as_view(), name='deletereview'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User
#import uuid

class Blog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    #id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    
    def __str__(self):
        return self.title

class Review(models.Model):
    VOTE_VALUE = (
        ('up','up'),('down','down')
    )
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    body = models.TextField()
    vote = models.CharField(max_length=10, choices=VOTE_VALUE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    #id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    
    def __str__(self):
        return self.vote

base/forms.py
from django.forms import ModelForm
from .models import Review

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['vote', 'body']

base/views.py
from typing import Any
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse

from .models import Blog, Review
from .forms import ReviewForm

from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django import forms

from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin 
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth import login

#User Authentication

class UserLogin(LoginView):
    template_name = 'base/login.html'
    fields = '__all__'
    redirect_authenticated_user = True
    
    def get_success_url(self):
        return reverse_lazy('blogs')

class RegisterUser(FormView):
    form_class = UserCreationForm
    template_name = 'base/register.html'
    success_url = reverse_lazy('blogs')
    
    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterUser, self).form_valid(form)
    
    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('blogs')
        return super(RegisterUser, self).get(*args, **kwargs)

#Blog CRUD
class BlogList(ListView):
    model = Blog
    template_name = 'base/blogs.html'
    context_object_name = 'blogs'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search = self.request.GET.get('search_item') or ''
        if search:
            context['blogs'] = context['blogs'].filter(title__startswith=search)
        context['search'] = search
        
        return context
    
class BlogDetails(DetailView):
    model = Blog
    template_name = 'base/blog.html'
    context_object_name = 'blog'
        
class BlogCreate(LoginRequiredMixin, CreateView):
    model = Blog
    template_name = 'base/createblog.html'
    fields = ['title', 'description']
    success_url = reverse_lazy('blogs')
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
    
class BlogUpdate(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ['title', 'description']
    template_name = 'base/createblog.html'
    success_url = reverse_lazy('blogs')
    
    
class BlogDelete(LoginRequiredMixin, DeleteView):
    model = Blog
    template_name = 'base/deleteconfirm.html'
    success_url = reverse_lazy('blogs')
    
#Reviews
class ReviewCreate(LoginRequiredMixin, CreateView):
    
    model = Review
    template_name = 'base/createreview.html'
    form_class = ReviewForm
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.blog_id = self.kwargs['pk']
        return super().form_valid(form)
    
    
    success_url = reverse_lazy('blogs')   

class ReviewUpdate(LoginRequiredMixin, UpdateView):
    model = Review
    fields = ['body', 'vote']
    template_name = 'base/createreview.html'
    success_url = reverse_lazy('blogs')
    
class ReviewDelete(LoginRequiredMixin, DeleteView):
    model = Review
    template_name = 'base/deleteconfirmreview.html'
    success_url = reverse_lazy('blogs')

base/templates/base/blog.html
{% extends "base/main.html" %}


{% block content %}

<main class="singleProject my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <h3 class="singleProject__subtitle">Edit Options:</h3>
          <div class="singleProject__toolStack">
            {% if request.user == blog.user %}
            <span class="tag tag--pill tag--sub tag--lg">
              <a href='{% url "updateblog" blog.id %}'><small>Edit</small></a>
            </span>
            <span class="tag tag--pill tag--sub tag--lg">
              <a href='{% url "deleteblog" blog.id %}'><small>Delete</small></a>
            </span>
            {% else %}
            <span class="tag tag--pill tag--sub tag--lg">
              <small>Only author can edit this</small>
            </span>
            {% endif %}
          </div>

        </div>
        <div class="column column--2of3">
          <h1 class="singleProject__developer">{{blog.user}}</h1>
          <h2 class="singleProject__title">{{blog.title}}</h2>
          <h3 class="singleProject__subtitle">Content...</h3>
          <div class="singleProject__info">{{blog.description|linebreaksbr}}</div>

          <div class="comments">
            <h3 class="singleProject__subtitle">Feedback</h3>

            {% comment %} <form class="form" action="#" method="POST">
              <!-- Textarea -->
              <div class="form__field">
                <label for="formInput#textarea">Comments: </label>
                <textarea class="input input--textarea" name="message" id="formInput#textarea"
                  placeholder="Write your comments here..."></textarea>
              </div>
              <input class="btn btn--sub btn--lg" type="submit" value="Comments" />
            </form> {% endcomment %}
            <a href='{% url "addreview" blog.id %}'>Add Comment</a><hr>
            <div class="commentList">
              {% for review in blog.review_set.all %}
              <div class="comment">
                
                <div class="comment__details">
                  <p class="comment__author"><strong>{{review.user}}</strong>: {{review.vote}} vote</p>
                  <p class="comment__info">Created : {{review.created}}  {% if review.created != review.updated %}<p>Updated : {{review.updated}}</p>{% endif %}</p>  

                  <p class="comment__info">{{review.body|linebreaksbr}}</p>
                  {% if request.user == review.user %}
                  <a href='{% url "updatereview" review.id %}'>Edit</a> <a href='{% url "deletereview" review.id %}'>Delete</a> 
                  {% endif %}
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  </main>

    
{% endblock content %}    
    


base/templates/base/blogs.html
{% extends "base/main.html" %}
{% block content %}

<main class="projects">
  <section class="hero-section text-center">
    <div class="container container--narrow">
      <div class="hero-section__box">
        <h2>Search for <span>Blogs</span></h2>
      </div>

      <div class="hero-section__search">
        <form class="form" method="GET">
          <div class="form__field">
            <label for="formInput#search">Search By Blogs </label>
            <input class="input input--text" type='text' name='search_item' placeholder="Search by Blog Title" value="{{search}}">
          </div>

          <input class="btn btn--sub btn--lg" type="submit" value="Search" />
        </form>
      </div>
    </div>
  </section>



  <section class="projectsList">
    <div class="container">
      <div class="grid grid--three">

        {% for blog in blogs %}  
        <div class="column">
          <div class="card project">
            <a href='{% url "blog" blog.id %}' class="project">
              
              <div class="card__body">
                <h3 class="project__title">{{blog.title}}</h3>
                <p><a class="project__author" href=""></a>{{blog.user}}</p>
              </div>
              
            </a>
          </div>
        </div>
        {% endfor %}

      </div>
    </div>
  </section>
</main>
{% endblock content %}

base/templates/base/createblog.html
{% extends "base/main.html" %}
{% block title %}Add Blog{% endblock title %}
{% block content %}

<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'blogs' %}"><i class="im im-angle-left"><</i></a>
            <br>
            <h1>Please fill details</h1>
            <form class="form" method="POST" action="">
                <!-- Input:Text -->
                {% csrf_token %}
                {% for field in form %}
                <div class="form__field">
                    <label for="formInput#text">{{field.label}}</label>
                    {{field}}
                </div>
                {% endfor %}
                
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock content %}

base/templates/base/createreview.html
{% extends "base/main.html" %}
{% block title %}Add Comment{% endblock title %}
{% block content %}



<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'blogs' %}"><i class="im im-angle-left"><</i></a>
            <br>
            <h1>Please fill details</h1>
            <form class="form" method="POST" action="">
                <!-- Input:Text -->
                {% csrf_token %}
                {% for field in form %}
                <div class="form__field">
                    <label for="formInput#text">{{field.label}}</label>
                    {{field}}
                </div>
                {% endfor %}
                
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock content %}



base/templates/base/deleteconfirm.html
{% extends "base/main.html" %}
{% block title %}Confirm Delete{% endblock title %}
{% block content %}

<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'blogs' %}"><i class="im im-angle-left"><</i></a>
            <br>
            <h1>Are your sure you want to delete this blog?</h1>
            <form class="form" method="POST" action="">
                {% csrf_token %}
                
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Delete" />
            </form>
        </div>
    </div>
</main>
{% endblock content %}

base/templates/base/deleteconfirmreview.html
{% extends "base/main.html" %}
{% block title %}Confirm Delete{% endblock title %}
{% block content %}

<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'blogs' %}"><i class="im im-angle-left"><</i></a>
            <br>
            <h1>Are your sure you want to delete this comment?</h1>
            <form class="form" method="POST" action="">
                {% csrf_token %}
                
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Delete" />
            </form>
        </div>
    </div>
</main>
{% endblock content %}

base/templates/base/login.html
{% extends "base/main.html" %}
{% block title %}Login{% endblock title %}
{% block content %}

<h1 style="padding-left: 10px;">Login</h1>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input class="button" type="submit" value="Login">
    </form>
    <p>Don't have an account? <a href="{% url 'register' %}">Register</a></p>
</div>

{% endblock content %}

base/templates/base/main.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}Adi's BlogPage{% endblock title %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
        <link rel="stylesheet" href="{% static 'styles/app.css' %}" />

    </head>
    <body>
        {% include 'base/navbar.html' %}
        {% block content %}


        {% endblock content %}
        {% comment %} <script src="" async defer></script> {% endcomment %}
    </body>
</html>

base/templates/base/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href='{% url "blogs" %}'>BlogPage</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href='{% url "blogs" %}'>Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'addblog' %}">Add Blog</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link disabled" href='{% url "logout" %}'>Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link disabled" href='{% url "login" %}'>Login</a>
        </li>
        {% endif %}
      </ul>
      <span style="padding-right: 10px;"  class="navbar-text">
        {{request.user|title}}
      </span>
    </div>
  </nav>

base/templates/base/register.html
{% extends "base/main.html" %}
{% block title %}Register{% endblock title %}
{% block content %}

<h1 style="padding-left: 10px;">Register</h1>
<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        {% csrf_token %}
        {{form.as_p}}
        <input class="button" type='submit' value='SignUp' />
    </form>
    <p>Already have an account? <a href="{% url 'login' %}">Login</a></p>
</div>

{% endblock content %}